### ISSUE TITLE
[saw-remote-api] xxHash verification stalls

### ISSUE THREAD

**Issue by WeeknightMVP** [GaloisInc/saw-script#1411]
I'm trying to verify a [reference implementation of 32-bit xxHash](https://github.com/easyaspi314/xxhash-clean/blob/master/xxhash32-ref.c) (the same one as in [saw-demos](https://github.com/GaloisInc/saw-demos)) using the most recent PyPI version of the [SAW Remote API for Python](https://pypi.org/project/saw-client/0.8.1), but my attempt stalls when trying to verify `XXH32_avalanche` or `XXH32_round` against a respective contract based on [xxhash.cry](https://github.com/GaloisInc/saw-demos/blob/master/demos/xxhash/xxhash.cry):

```python
# xxhashref-32.py

from saw_client import LogResults, connect, cryptol_load_file, llvm_load_module, llvm_verify, view
from saw_client.llvm import Contract, cryptol, i32

class Contract_XXH_rotl32(Contract):
    def specification(self) -> None:
        value = self.fresh_var(i32, "value")
        amt = self.fresh_var(i32, "amt")

        self.execute_func(value, amt)

        self.returns( cryptol("(<<<)")(value, amt) )

class Contract_XXH32_round(Contract):
    def specification(self) -> None:
        acc = self.fresh_var(i32, "acc")
        input_ = self.fresh_var(i32, "input")

        self.execute_func(acc, input_)

        self.returns( cryptol("XXH32_round")(acc, input_) )

class Contract_XXH32_avalanche(Contract):
    def specification(self) -> None:
        hash_ = self.fresh_var(i32, "hash")

        self.execute_func(hash_)

        self.returns( cryptol("XXH32_avalanche")(hash_) )

if __name__ == '__main__':
    connect(reset_server=True)
    view(LogResults())

    bcname = 'xxhash32-ref.bc'
    cryname = 'xxhash.cry'

    cryptol_load_file(cryname)

    mod = llvm_load_module(bcname)

    # verifies
    result_XXH_rotl32 = llvm_verify(
        module=mod,
        function='XXH_rotl32',
        contract=Contract_XXH_rotl32()
    )

    # hangs
    result_XXH32_round = llvm_verify(
        module=mod,
        function='XXH32_round',
        contract=Contract_XXH32_round(),
        lemmas=[result_XXH_rotl32]
    )

    # also hangs, even with other `llvm_verify` calls commented out
    result_XXH32_avalanche = llvm_verify(
        module=mod,
        function='XXH32_avalanche',
        contract=Contract_XXH32_avalanche()
    )
```

```
$ poetry run python3 xxhash32-ref.py
The currently activated Python version 3.6.9 is not supported by the project (^3.8).
Trying to find and use a compatible version.
Using python3.9 (3.9.6)
✅  Verified: lemma_Contract_XXH_rotl32 (defined at .../workspace/xxhash-issue/xxhash32-ref.py:36)

[ hangs ]
```

This suggests some problem with loading and calling a declaration from `xxhash.cry`, as `XXH_rotl32` can be verified and does not depend on `xxhash.cry`.

```toml
# pyproject.toml

[tool.poetry]
name = "saw-remote-api-issue"
version = "0.0.1"
readme = "README.md"
description = "saw-remote-api issue with xxhash"
authors = []
license = "BSD License"
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.8"
saw-client = "0.8.1"

[build-system]
requires = ["poetry>=1.1.4", "setuptools>=40.8.0"]
```
